### PR TITLE
Addition of pissing status effect

### PR DESCRIPTION
**Pull request by WarpedCakez**
It works.... kinda. I fear this won't work in multiplayer and I'm rusty on java so feel free to roast me.

### CODE REVIEW

**Comment by WarpedCakez** [comment]
Oh hell nah. I gotta fix everything since you changed the name of the base class

**Comment by WarpedCakez** [comment]
If you want to test the status effect, type this command: `/effect give @p diapersplus:pissing 19`

**Review by rowleynt — APPROVED** [review]
I'm sure that there's a better way to freeze the player in place, but this is good enough for now.

**Review by Baeverette — APPROVED** [review]

**Review by BryceWren — COMMENTED** [review]
this is very funny 

getPissingSpotX Y and Z haha

**Pull request merged**
